#!/bin/bash

# FXC cannot be run from MinGW, there's a bug with paths.
cmd /C"fxc /Tfx_2_0 src\graphics\effects\PostProcess.fx /FoPostProcess.xnb"
mv PostProcess.xnb bin/Debug/Content/effects

cmd /C"fxc /Tfx_2_0 src\graphics\effects\SpiritRealm.fx /FoSpiritRealm.xnb"
mv SpiritRealm.xnb bin/Debug/Content/effects

cmd /C"fxc /Tfx_2_0 src\graphics\effects\SolidThing.fx /FoSolidThing.xnb"
mv SolidThing.xnb bin/Debug/Content/effects
